advertiser/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from common import views
from django.conf.urls import include
from rest_framework import routers
from django.views.generic import TemplateView
from views import CampaignViewSet, CampaignResourceViewSet,\
    CampaignHoardingsViewSet, AdvertiserHome, CreateCampaignView, CampaignDetail, Inventory
from models import Campaign, CampaignHoardings

router = routers.DefaultRouter()
router.register(r'campaign', CampaignViewSet, Campaign)
router.register(r'resource', CampaignResourceViewSet, Campaign)
router.register(r'campaign-hoardings', CampaignHoardingsViewSet,CampaignHoardings)
urlpatterns = router.urls

urlpatterns = [

    url(r'/create/campaign$', CreateCampaignView.as_view()),
    url(r'/campaign/(?P<id>\d+)/$', CampaignDetail.as_view()),
    url(r'/inventory/$', Inventory.as_view()),
    url(r'/api/', include(router.urls)),
    url(r'/$', AdvertiserHome.as_view()),
    # url(r'ad-upload/', TemplateView.as_view(template_name='file-upload.html')),
    # url(r'create-campaign/', TemplateView.as_view(template_name='create-campaign.html')),
    # url(r'choose-hoarding/', TemplateView.as_view(template_name='choose-hoarding.html')),

]

common/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from common import views
from django.conf.urls import include
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'city', views.CityViewSet)
router.register(r'state', views.StateViewSet)
router.register(r'country', views.CountryViewSet)
router.register(r'address', views.AddressViewSet)
urlpatterns = router.urls
urlpatterns = [
    url(r'^', include(router.urls)),
]

flexplex/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from django.contrib import admin
from quickstart import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
#from hoarder.views import HoardingDetail, HoardingList

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^common/', include('common.urls')),
    url(r'advertiser', include('advertiser.urls')),
    url(r'hoarder', include('hoarder.urls')),
    url(r'', include('authentication.urls')),
    url(r'', include('emailcampaign.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertiser/models.py
from __future__ import unicode_literals

# models.py
import uuid
from django.db import models
import os
from datetime import date
from django.db.models import Sum

class Campaign(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey('auth.User')
    name = models.CharField(default='', max_length=100)
    resource = models.FileField(null=True)
    duration = models.PositiveIntegerField(default=15)
    from_date = models.DateField(null=True)
    to_date = models.DateField(null=True)
    CONTENT_STATUS_TYPE_CHOICES = (
        (0, 'Pending'),
        (1, 'Approved'),
        (2, 'Rejected'),
    )
    content_status = models.IntegerField(choices=CONTENT_STATUS_TYPE_CHOICES, default=0)
    creation_date = models.DateTimeField(auto_now_add=True)

    def isVideo(self):
        name, extension = os.path.splitext(self.resource.name)
        if extension == '.mp4':
            return True
        else:
            return False

    def get_status(self):
        if self.to_date < date.today():
            return 'Expired'
        elif self.from_date <= date.today() and self.to_date >= date.today():
            return 'Running'
        else:
            return 'Scheduled'



class CampaignHoardings(models.Model):
    campaign = models.ForeignKey('Campaign', related_name='hoardings', on_delete=models.CASCADE)
    hoarding = models.ForeignKey('hoarder.Hoarding', related_name='campaigns')
    STATUS_TYPE_CHOICES = (
        (0, 'Pending'),
        (1, 'Accepted'),
        (2, 'Rejected'),
    )
    status = models.IntegerField(choices=STATUS_TYPE_CHOICES, default=0)

    def get_total_impression_count(self):
        total_impressions = CampaignImpressions.objects.filter(hoarding=self.hoarding, campaign=self.campaign).aggregate(Sum('impression_count'))
        if total_impressions['impression_count__sum'] is None:
            return 0
        else:
            return total_impressions['impression_count__sum']

    def get_todays_impression_count(self):
        campaign_impressions = CampaignImpressions.objects.filter(hoarding=self.hoarding, campaign=self.campaign,
                                                                         date=date.today()).first()
        if campaign_impressions is None:
            return 0
        else:
            return campaign_impressions.impression_count

class CampaignImpressions(models.Model):
    date = models.DateField(null=True)
    campaign = models.ForeignKey('Campaign', on_delete=models.CASCADE)
    hoarding = models.ForeignKey('hoarder.Hoarding')
    impression_count = models.IntegerField(default=0)

advertiser/views.py
# views.py
import os
from subprocess import call

from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.viewsets import ModelViewSet
from advertiser.models import Campaign, CampaignHoardings
from advertiser.serializers import CampaignSerializer, CampaignResourceSerializer, CampaignHoardingsSerializer
from hoarder.models import Hoarding, get_active_hoardings
from django.shortcuts import render
from rest_framework.generics import GenericAPIView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.utils.dateparse import parse_datetime
from django.core.files.storage import FileSystemStorage
from rest_auth.views import APIView
from datetime import datetime
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from emailcampaign.cron import email_scheduled_job

class CampaignResourceViewSet(ModelViewSet):
    # queryset = Campaign.objects.all()
    serializer_class = CampaignResourceSerializer
    parser_classes = (MultiPartParser, FormParser,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user,
                        resource=self.request.data.get('resource'))

    def get_queryset(self):
        queryset = Campaign.objects.filter(user=self.request.user)
        return queryset


class CampaignViewSet(ModelViewSet):
    # queryset = Campaign.objects.all()
    serializer_class = CampaignSerializer

    # parser_classes = (MultiPartParser, FormParser,)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user,
                        resource=self.request.data.get('resource'))

    def get_queryset(self):
        queryset = Campaign.objects.filter(user=self.request.user)
        return queryset


class CampaignHoardingsViewSet(ModelViewSet):
    # queryset = CampaignHoardings.objects.all()
    # queryset = CampaignHoardings.objects.none()
    serializer_class = CampaignHoardingsSerializer(many=True)

    def get_queryset(self):
        user = self.request.user
        campaigns = Campaign.objects.filter(user=user)
        return CampaignHoardings.objects.all()


class AdvertiserHome(View):
    @method_decorator(login_required)
    def get(self, request):
        campaigns = Campaign.objects.filter(user=self.request.user).order_by('-to_date')
        # for campaign in campaigns:
        #     hoardings = CampaignHoardings.objects.filter(campaign=campaign)
        #     campaign.hoardings['hoardings'] = hoardings

        # email = EmailMessage('Subject', 'Body', to=['rushikesh.talokar@gmail.com'])
        # email.send()

        # subject, from_email, to = 'Html Test', 'admin@flexplex.in ', 'rushikesh.talokar@gmail.com'
        #
        # html_content = render_to_string('email/cerberus-responsive.html', {'varname': 'value'})  # ...
        # text_content = strip_tags(html_content)  # this strips the html, so people will have the text as well.
        #
        # # create the email, and attach the HTML version as well.
        # msg = EmailMultiAlternatives(subject=subject, body=text_content, from_email=from_email, to=[to])
        # msg.attach_alternative(html_content, "text/html")
        # msg.send()
        # email_scheduled_job(request)

        return render(request, 'advertiser/index.html',
                      {'campaigns': campaigns})


def create_campaign(request, status=CampaignHoardings.STATUS_TYPE_CHOICES[0][0]):
    myfile = request.FILES['resource']
    fs = FileSystemStorage()
    fs.location += '/campaigns'
    fs.base_url += 'campaigns'
    filename = fs.save(myfile.name, myfile)
    if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.mp4')):
        outFileName = os.path.splitext(filename)[0] + '.mp4'

        if not filename.lower().endswith(('.mp4')):
            ffmpegCmd = 'ffmpeg -loop 1 -i ' \
                        + fs.location + "/" + filename + ' -c:v libx264 -t 10 -pix_fmt yuv420p -vf scale=1280:720 ' \
                        + fs.location + "/" + outFileName

            # local

            # ffmpegCmd = 'ffmpeg -loop 1 -i ' \
            #             + fs.location + "/" + filename + ' -c:v libx264 -t 10 -pix_fmt yuv420p -vf scale=1280:720 ' \
            #             + fs.location + "/" + outFileName
            process = call(ffmpegCmd, shell=True)

        ##AVI File
        aviFileName = os.path.splitext(filename)[0] + '.avi'
        ffmpegCmd = 'ffmpeg -i ' \
                    + fs.location + "/" + outFileName + ' -vcodec mpeg4 ' \
                    + fs.location + "/" + aviFileName
        process = call(ffmpegCmd, shell=True)

        # process.wait()
        filename = outFileName

    uploaded_file_url = fs.base_url + "/" + filename

    campaign = Campaign(user=request.user,
                        name=request.POST['name'],
                        from_date=request.POST['from_date'],
                        to_date=request.POST['to_date'],
                        resource=uploaded_file_url)
    campaign.save()
    for hoarding_id in request.POST.getlist('hoardings'):
        hoarding = Hoarding.objects.get(id=hoarding_id)
        CampaignHoardings.objects.create(campaign=campaign, hoarding=hoarding, status=status)
        hoarding.save()


class CreateCampaignView(View):
    def get(self, request):
        queryset = get_active_hoardings()
        return render(request, 'advertiser/campaign-wizard.html', {'hoardings': queryset})

    def post(self, request, *args, **kwargs):
        create_campaign(request)
        return HttpResponseRedirect('../')


class CampaignDetail(View):
    def get(self, request, id):
        campaign = Campaign.objects.get(id=id)
        return render(request, 'advertiser/campaign-detail.html', {'campaign': campaign})


class Inventory(GenericAPIView):
    def get(self, request):
        queryset = get_active_hoardings()
        return render(request, 'advertiser/inventory.html', {'hoardings': queryset})

templates/advertiser/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="../../static/img/ico/favicon.png">

    <title>Advertiser Console | Flexplex </title>

    <!-- Bootstrap -->
    <link href="/static/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/static/gentelella/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/static/gentelella/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="/static/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="/static/gentelella/build/css/custom.css" rel="stylesheet">


</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col">
            {% include "advertiser/sidebar.html" %}
        </div>

        {% include "advertiser/header.html" %}

        <!-- Scripts -->
        <!-- jQuery -->
        <script src="/static/gentelella/vendors/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap -->
        <script src="/static/gentelella/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/static/gentelella/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/static/gentelella/vendors/nprogress/nprogress.js"></script>
        <!-- Chart.js -->
        <script src="/static/gentelella/vendors/Chart.js/dist/Chart.min.js"></script>
        <!-- jQuery Sparklines -->
        <script src="/static/gentelella/vendors/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
        <!-- Flot -->
        <script src="/static/gentelella/vendors/Flot/jquery.flot.js"></script>
        <script src="/static/gentelella/vendors/Flot/jquery.flot.pie.js"></script>
        <script src="/static/gentelella/vendors/Flot/jquery.flot.time.js"></script>
        <script src="/static/gentelella/vendors/Flot/jquery.flot.stack.js"></script>
        <script src="/static/gentelella/vendors/Flot/jquery.flot.resize.js"></script>
        <!-- Flot plugins -->
        <script src="/static/gentelella/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
        <script src="/static/gentelella/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
        <script src="/static/gentelella/vendors/flot.curvedlines/curvedLines.js"></script>
        <!-- DateJS -->
        <script src="/static/gentelella/vendors/DateJS/build/date.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/static/gentelella/vendors/moment/min/moment.min.js"></script>
        <script src="/static/gentelella/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <script src="/static/gentelella/vendors/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
        <!-- Custom Theme Scripts -->
        <script src="/static/gentelella/build/js/custom.js"></script>

        <!-- page content -->
        <div class="right_col" role="main">
            {#        {% include "header.html" %}#}
            {% block content %}
            {% endblock content %}

        </div>
        <!-- /page content -->

        {% include "advertiser/footer.html" %}
    </div>
</div>
</body>

</html>

templates/advertiser/campaign-detail.html
{% extends "advertiser/base.html" %}
{% block content %}
    <div class="row">
        <div class="panel panel-default col-md-12">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-5" style="padding: 0px">
                        {% if campaign.isVideo %}
                            <video width="100%" controls>
                                <source src="{{ campaign.resource }}" type="video/mp4">
                            </video>
                        {% else %}
                            <img src="{{ campaign.resource }}" class="img-rounded" width="100%">
                        {% endif %}
                    </div>
                    <div class="col-md-7">
                        <h3>{{ campaign.name }}</h3>
                        <table data-toggle="table" data-striped="true">
                            <thead>
                            <tr>
                                <td style="width: 150px"></td>
                                <td style="width: 20px"></td>
                                <td></td>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><label>Schedule</label></td>
                                <td>:</td>
                                <td>{{ campaign.from_date }} to {{ campaign.to_date }}</td>
                            </tr>
                            <tr>
                                <td><label>Total Hoardings</label></td>
                                <td>:</td>
                                <td> {{ campaign.hoardings.count }} </td>
                            </tr>
                            <tr>
                                <td><label>Campaign Status</label></td>
                                <td>:</td>
                                <td>{% if  campaign.get_status == 'Scheduled' %}
                                    <span class="label label-primary">{{ campaign.get_status }}</span>
                                {% elif campaign.get_status == 'Running' %}
                                    <span class="label label-success">{{ campaign.get_status }}</span>
                                {% elif campaign.get_status == 'Expired' %}
                                    <span class="label label-danger">{{ campaign.get_status }}</span>
                                {% endif %}</td>
                            </tr>
                             <tr>
                                <td><label>Content Approval</label></td>
                                <td>:</td>
                                <td> {% if campaign.content_status == 2 %}
                            <span class="label label-danger">{{ campaign.get_content_status_display }}</span>
                        {% elif campaign.content_status == 1 %}
                            <span class="label label-success">{{ campaign.get_content_status_display }}</span>
                        {% else %}
                            <span class="label label-warning">{{ campaign.get_content_status_display }}</span>
                        {% endif %}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                <br/>

                <div class="row">
                    <h2>Hoardings List</h2>
                    <table class="table table-striped jambo_table table-bordered">
                        <thead>
                        <tr class="headings">
                            <th>Hoarding</th>
                            <th>Cost</th>
                            <th>Dimension</th>
                            <th>Impressions</th>
                            <th>Publisher Approval</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for hoarding in campaign.hoardings.all %}
                            <tr>
                                <td>{{ hoarding.hoarding.address.address }}, {{ hoarding.hoarding.address.city.name }}</td>
                                <td>{{ hoarding.hoarding.cost }}</td>
                                <td>{{ hoarding.hoarding.width }} x {{ hoarding.hoarding.height }} ft.</td>
                                <td>{{ hoarding.get_total_impression_count }}</td>
                                {% if hoarding.status == 2 %}
                                    <td><span class="label label-danger">{{ hoarding.get_status_display }}</span></td>
                                {% elif hoarding.status == 1 %}
                                    <td><span class="label label-success">{{ hoarding.get_status_display }}</span></td>
                                {% else %}
                                    <td><span class="label label-warning">{{ hoarding.get_status_display }}</span></td>
                                {% endif %}

                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <link rel="stylesheet" href="https://cdn.plyr.io/2.0.12/plyr.css">
    <script src="https://cdn.plyr.io/2.0.12/plyr.js"></script>
    <script>plyr.setup();</script>
    <style>
        .plyr--stopped .plyr__controls {

            opacity: 0;

        }
    </style>
{% endblock content %}

templates/advertiser/campaign-wizard.html
{% extends "advertiser/base.html" %}
{% block content %}
    <style>
        .viewport-height {
            height: 60vh;
        }
    </style>
    <script src="/static/gentelella/vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
    <!-- Smart Wizard -->
    <div class="">
        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel" style="padding: 0px">
                    <div class="x_title" style="padding: 10px">
                        <h2>Create New Campaign
                            <small>Fill below information carefully</small>
                        </h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div id="wizard" class="form_wizard wizard_horizontal">
                            <ul class="wizard_steps row" style="padding: 0px">
                                <li class="col-md-4" style="padding: 0px">
                                    <a id="step-anchor-1" href="#step-1">
                                        <span class="step_no">1</span>
                                        <span class="step_descr">
                                              Basic details<br/>
                                              <small></small>
                                          </span>
                                    </a>
                                </li>
                                <li class="col-md-4" style="padding: 0px" onclick="resizeMap();">
                                    <a id="step-anchor-2" href="#step-2">
                                        <span class="step_no">2</span>
                                        <span class="step_descr">
                                              Select Screens<br/>
                                              <small></small>
                                          </span>
                                    </a>
                                </li>
                                <li class="col-md-4" style="padding: 0px">
                                    <a id="step-anchor-3" href="#step-3">
                                        <span class="step_no">3</span>
                                        <span class="step_descr">
                                              Publish<br/>
                                              <small></small>
                                          </span>
                                    </a>
                                </li>
{#                                <li class="col-md-3" style="padding: 0px">#}
{#                                    <a id="step-anchor-4" href="#step-4">#}
{#                                        <span class="step_no">3</span>#}
{#                                        <span class="step_descr">#}
{#                                              Preview<br/>#}
{#                                              <small></small>#}
{#                                          </span>#}
{#                                    </a>#}
{#                                </li>#}
                            </ul>
                            <form id="wizard-1" novalidate="novalidate" action="" method="post"
                                  enctype="multipart/form-data">
                                {% csrf_token %}
                                <div id="step-1" class="viewport-height">
                                    {#                                <h2 class="StepTitle" style="margin: 10px">Fill Campaign Details:</h2>#}
                                    {% include "advertiser/file-upload.html" %}
                                </div>
                                <div id="step-2" class="viewport-height">
                                    <h2 class="StepTitle" style="margin: 10px">Select Hoarding:</h2>
                                    {% include "advertiser/choose-hoarding.html" %}
                                </div>
                                <div id="step-3" class="viewport-height">
                                    <h2 class="StepTitle" style="margin: 10px">Publish:</h2>
                                    <div style="margin-top: 180px;height: 330px; text-align: center">
                                        <button type="submit" class="btn btn-primary" style="width: 150px">
                                            <i class="fa fa-cloud-upload fa-4x" aria-hidden="true"></i> <br/>Publish
                                        </button>
                                    </div>
                                </div>
{#                                <div id="step-4" class="viewport-height">#}
{#                                   <div class="col-md-4" style="text-align: -webkit-center">#}
{#                                       <div style="width: 450px; height: 300px;border-style: solid;border-width: 5px;"></div>#}
{#                                   </div>#}
{#                                    <div class="col-md-4" style="text-align: -webkit-center">#}
{#                                       <div style="width: 300px; height: 300px;border-style: solid;border-width: 5px;"></div>#}
{#                                   </div>#}
{#                                     <div class="col-md-4" style="text-align: -webkit-center">#}
{#                                       <div style="width: 300px; height: 450px;border-style: solid;border-width: 5px;"></div>#}
{#                                   </div>#}
{#                                </div>#}
                            </form>
                        </div>
                        <!-- End SmartWizard Content -->

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End SmartWizard Content -->

{% endblock content %}

templates/advertiser/footer.html
<!-- footer content -->
<footer>
    <div class="pull-right">
        © 2017 <a href="">Altus Software</a>
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->

templates/advertiser/header.html
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">

                <li class="">
                    {% if user.is_authenticated %}
                        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                           aria-expanded="false">
                            <img src="/static/img/avatar-black.png" alt="">{{ user.first_name }}
                            <span class=" fa fa-angle-down"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-usermenu pull-right">
                            <li><a href="/"> Home</a></li>
                            <li><a href=""> Profile</a></li>
                            {% if user.is_superuser %}
                                <li><a href="/advertiser">Advertiser Console</a></li>
                                <li><a href="/hoarder">Publisher Console</a></li>
                            {% endif %}
                            <li><a href="{% url 'logout' %}?next=/"><i class="fa fa-sign-out pull-right"></i>
                                Log Out</a></li>
                        </ul>
                    {% else %}
                        <a href="/signin">Login</a>
                    {% endif %}
                </li>

                <!--<li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                       aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image"/></span>
                                <span>
                                          <span>John Smith</span>
                                          <span class="time">3 mins ago</span>
                                        </span>
                                <span class="message">
                                          Film festivals used to be do-or-die moments for movie makers. They were where...
                                        </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li> -->
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

templates/advertiser/inventory.html
{% extends "advertiser/base.html" %}
{% block content %}
    <style>
        .viewport-height {
            height: 90vh;
        }
    </style>

    {% include "advertiser/choose-hoarding.html" %}
{% endblock content %}